# Generated by Django 5.1.7 on 2025-04-16 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='category/'),
        ),
        migrations.AddField(
            model_name='product',
            name='isbestseller',
            field=models.BooleanField(default=False),
        ),
    ]
