# Generated by Django 5.1.7 on 2025-04-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_category_image_product_isbestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
