# Generated by Django 5.1.7 on 2025-04-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_banner_description_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='title_color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
